parameters:
  ros_master_port: 11311
  rpc_port: 11611
  master_sync: true
  topic_list_paths_incoming: /ws/example/2_single_machine_multimaster/listener/talker_topic.txt

windows:
  - name: LISTEN
    splits:
      - commands:
        - rostopic echo /chatter