parameters:
  ros_ip_key: machine_b_ip
  ros_master_hostname_key: machine_b_ip
  discover_host_keys: machine_a_ip
windows:
  - name: TALK
    splits:
      - commands:
        - |
          rostopic pub /chatter std_msgs/String "data: 'hello from talker'"