before-command: {}
common:
  before_commands:
  - if [ '${before_command}' != "None" ]; then ${before_command}; fi
  - if [ '${ros_ip_key}' != "None" ]; then export ROS_IP=$(/ws/session/content/get_data_dict_entries.py
    -k "${ros_ip_key}") && echo ${ROS_IP}; fi
  - export ROS_MASTER_URI=http://$(/ws/session/content/get_data_dict_entries.py -k
    "${ros_master_hostname_key}"):${ros_master_port}
parameters:
  before_command: null
  check_host: false
  dir_path: null
  discover_host_keys: machine_a_ip + machine_b_ip
  master_discovery: true
  master_sync: true
  rec: false
  rec_command_1: rosbag record --split --size=5120 -o ${dir_path}/rec_sync_ -e '(.*)_sync$'
  rec_command_2: null
  rec_command_3: null
  rec_command_4: null
  remove_target_prefix_incoming: null
  ros_core: false
  ros_ip_key: machine_b_ip
  ros_master_hostname_key: localhost
  ros_master_port: 11311
  rpc_port: 11611
  session_dir: /ws/example/5_showcase/machine_b
  sync_remote_nodes: true
  sync_suffix: _sync
  target_prefix_outgoing: null
  topic_list_paths_incoming: /ws/example/5_showcase/topics_a_to_b.txt
  topic_list_paths_outgoing: /ws/example/5_showcase/topics_b_to_a.txt
  topic_list_prefixes_incoming: ''
  topic_list_prefixes_outgoing: null
  topic_monitor: false
  topic_relay_incoming: true
  topic_relay_outgoing: true
windows:
- delay: 2.5
  if: ros_core
  layout: even-vertical
  name: CORE
  splits:
  - commands:
    - roscore --port ${ros_master_port}
  - commands:
    - sleep 2
    - rosparam set enable_statistics true
- delay: 1
  if: rec
  layout: even-vertical
  name: REC
  splits:
  - commands:
    - if [ "${rec_command_1}" == "None" ]; then exit; fi
    - ${rec_command_1}
  - commands:
    - if [ "${rec_command_2}" == "None" ]; then exit; fi
    - ${rec_command_2}
  - commands:
    - if [ "${rec_command_3}" == "None" ]; then exit; fi
    - ${rec_command_3}
  - commands:
    - if [ "${rec_command_4}" == "None" ]; then exit; fi
    - ${rec_command_4}
- if: master_discovery
  name: DISC
  splits:
  - commands:
    - /ws/session/content/base/start_fkie_master_discovery.py _discover_host_keys:="${discover_host_keys}"
      _rpc_port:=${rpc_port}
- if: master_sync
  name: SYNC
  splits:
  - commands:
    - /ws/session/content/base/start_fkie_master_sync.py _check_host:="${check_host}"
      _sync_remote_nodes:="${sync_remote_nodes}" _topic_list_prefixes:="${topic_list_prefixes_incoming}"
      _topic_list_paths:="${topic_list_paths_incoming}" _sync_suffix:="${sync_suffix}"
- if: topic_relay_incoming
  name: IN
  splits:
  - commands:
    - /ws/session/content/base/topic_relay_incoming.py _topic_list_prefixes:="${topic_list_prefixes_incoming}"
      _remove_target_prefix:="${remove_target_prefix_incoming}" _topic_list_paths:="${topic_list_paths_incoming}"
      _sync_suffix:="${sync_suffix}"
- if: topic_relay_outgoing
  name: OUT
  splits:
  - commands:
    - /ws/session/content/base/topic_relay_outgoing.py _topic_list_prefixes:="${topic_list_prefixes_outgoing}"
      _target_prefix:="${target_prefix_outgoing}" _topic_list_paths:="${topic_list_paths_outgoing}"
      _sync_suffix:="${sync_suffix}"
- if: topic_monitor
  name: TOP
  splits:
  - commands:
    - /ws/session/content/base/topic_monitor.py
- layout: even-vertical
  name: GOAL
  splits:
  - commands:
    - rostopic echo /move_base_simple/goal
  - commands:
    - rostopic echo /move_base_simple/goal_sync
- layout: even-vertical
  name: MAP_BW
  splits:
  - commands:
    - rostopic bw /costmap/costmap_compressed_sync
  - commands:
    - rostopic bw /costmap/costmap_compressed
  - commands:
    - rostopic bw /costmap/costmap
- layout: even-vertical
  name: MAP_HZ
  splits:
  - commands:
    - rostopic hz /costmap/costmap_compressed_sync
  - commands:
    - rostopic hz /costmap/costmap_compressed
  - commands:
    - rostopic hz /costmap/costmap
- name: COMP
  splits:
  - commands:
    - /ws/session/content/compression/universal_compressor.py _config:=/ws/example/5_showcase/machine_b/compression.yaml
